FROM eclipse-temurin:17
ARG BUILD_ID
ARG APP_NAME

ENV APP_NAME $APP_NAME
ENV APP_WORKDIR="/opt/admaru"
ENV USER_NAME="appuser"
ENV HEAP_OPTS="-Xms512M -Xmx512M"

RUN adduser "$USER_NAME"
RUN mkdir -p --mode=755 "$APP_WORKDIR/$APP_NAME/stored"
RUN chown -R "$USER_NAME":"$USER_NAME" "$APP_WORKDIR"

COPY ./target/${APP_NAME}.jar ${APP_WORKDIR}/${APP_NAME}/${APP_NAME}.jar
COPY ./config/{APP_NAME}-config.yaml.k8s ${APP_WORKDIR}/${APP_NAME}/{APP_NAME}-config.yaml
COPY ./config/{APP_NAME}-settings.yaml.k8s ${APP_WORKDIR}/${APP_NAME}/{APP_NAME}-settings.yaml

USER "$USER_NAME"

WORKDIR $APP_WORKDIR/$APP_NAME

EXPOSE 8080

CMD java -jar ${HEAP_OPTS} \
 -Dspring.config.additional-location=./{APP_NAME}-config.yaml \
 ${APP_NAME}.jar
